apiVersion: v1
kind: Service
metadata:
  name: nodejs-pod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: node-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
      - name: nodejd-pod
        image: wmbone/node-pod:1.1
        ports:
        - containerPort: 8080